from geopy.geocoders import Nominatim
import json
geolocator = Nominatim(user_agent="MyApp")
cities=[
    'Shimla',
    'Ooty',
    'Munnar',
    'Hyderabad',
    'mysore',
    'mahabalipuram',
    'kedarnath',
    'Mahabaleshwar',
    'Mussoorie',
    'Coorg',
    'Darjeeling',
    'Nainital',
    'Manali',
    'Andaman Islands',
    'Lachung',
    'Almora',
    'Dalhousie',
    'Pelling',
    'Lonavala',
    'Kullu',
    'Cherrapunji',
    'Shillong',
    'Dharamshala',
    'Wayanad',
    'Gangtok',
    'Chikmagalur',
    'Kodaikanal',
    'Thekkady',
    'Bangalore',
    'Panjim',
    'Agra',
    'Dandeli',
    'Valley Of Flowers',
    'Shivanasamudra Falls',
    'Hogenakkal',
    'Athirapally Waterfalls',
    'Srisailam',
    'Kumarakom',
    'Vizag',
    'Kochi',
    'Kovalam',
    'Puri',
    'Alleppey',
    'Pondicherry',
    'Somnath',
    'Shirdi',
    'Tirupati',
    'Haridwar',
    'Varanasi',
    'Trivandrum',
    'Guwahati',
    'Bhubaneswar',
    'Rameshwaram',
    'Rishikesh',
    'Sabarimala',
    'Kanyakumari',
    'Ganpatipule',
    ' Dwarka',
    'Mathura',
    'Gokarna',
    'Kedarnath',
    'Badrinath',
    'Vrindavan',
    'Murudeshwar',
    'Udupi',
    'Nashik',
    'Kumbakonam',
    'Delhi City',
    'Jaipur',
    'Ajanta Caves',
    'Amritsar',
    'Mysore',
    'Mumbai',
    'Hampi',
    'Madurai',
    'Udaipur',
    'Kanchipuram',
    'Hyderabad',
    'Jodhpur',
    'Ahmedabad',
    'Ellora Caves',
    'Khajuraho',
    'Konark',
    'Mahabalipuram',
    'Jaisalmer',
    'Thanjavur',
    'Rann Of Kutch',
    'Tiruchirappalli',
    'Alibaug',
    'Ajmer',
    'Bikaner',
    'Chidambaram',
    'Shravanabelagola',
    'Pune',
    'Gwalior',
    'Chittorgarh',
]
latLang={}
for i in cities:
    loc = geolocator.geocode(i)
    latLang[i]=[loc.latitude,loc.longitude]

json_string=json.dumps(latLang)
jsonFile = open("C:/Users/saket/Desktop/xwebsite/client/importdata/data.json", "w")
jsonFile.write(json_string)
jsonFile.close()
